
language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r greent/requirements.txt"
# command to run tests
script: "PYTHONPATH=./greent python greent/translator.py"
