name: robokop
channels:
- creditx
- defaults
dependencies:
- neo4jrestclient=2.1.1=pyh97ac0ba_0
- boto=2.48.0=py36_0
- bz2file=0.98=py36_0
- certifi=2016.2.28=py36_0
- cycler=0.10.0=py36_0
- decorator=4.1.2=py36_0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- gensim=2.3.0=np113py36_0
- glib=2.50.2=1
- icu=54.1=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.30=1
- libxml2=2.9.4=0
- matplotlib=2.0.2=np113py36_0
- mkl=2017.0.3=0
- networkx=1.11=py36_0
- nltk=3.2.4=py36_0
- numpy=1.13.1=py36_0
- openssl=1.0.2l=0
- pcre=8.39=1
- pip=9.0.1=py36_1
- py=1.4.34=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- pytest=3.2.1=py36_0
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- readline=6.2=2
- requests=2.14.2=py36_0
- scipy=0.19.1=np113py36_0
- setuptools=36.4.0=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- smart_open=1.5.3=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - appnope==0.1.0
  - argh==0.26.2
  - autovizwidget==0.12.4
  - bleach==2.1.1
  - bravado==9.0.2
  - bravado-core==4.9.1
  - cachier==1.2.1
  - chardet==3.0.4
  - click==6.7
  - colorama==0.3.9
  - dbus=1.10.20=0
  - entrypoints==0.2.3
  - flask==0.12
  - flask-graphql==1.4.1
  - flask-testing==0.6.2
  - gnureadline==6.3.3
  - graphene==1.4.1
  - graphql-core==1.1
  - graphql-relay==0.4.5
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=0
  - green==2.11.0
  - hdijupyterutils==0.12.4
  - html5lib==1.0b10
  - idna==2.5
  - ipykernel==4.6.1
  - ipython==4.2.1
  - ipython-genutils==0.2.0
  - ipywidgets==6.0.1
  - isodate==0.5.4
  - itsdangerous==0.24
  - jedi==0.11.0
  - jinja2==2.9.6
  - jsobject==0.10.2
  - jsonpath-rw==1.4.0
  - jsonschema==2.6.0
  - jupyter==1.0.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - jupyterlab==0.27.0
  - jupyterlab-launcher==0.5.1
  - libgcc=5.2.0=0
  - libxcb=1.12=1
  - markupsafe==1.0
  - marshmallow==2.13.6
  - mistune==0.7.4
  - mock==2.0.0
  - nbconvert==5.3.1
  - nbformat==4.4.0
  - neo4j-driver==1.4.0
  - nose==1.3.7
  - notebook==4.4.1
  - ontobio==0.2.19
  - pandas==0.20.3
  - pandocfilters==1.4.2
  - parso==0.1.0
  - pathtools==0.1.2
  - pbr==3.1.1
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - pkginfo==1.4.1
  - plotly==1.10.0
  - ply==3.10
  - portalocker==1.1.0
  - prefixcommons==0.1.4
  - promise==2.0.2
  - prompt-toolkit==1.0.15
  - pronto==0.8.0
  - ptyprocess==0.5.2
  - pygments==2.2.0
  - pykerberos==1.1.14
  - pyld==0.7.3
  - pysolr==3.6.0
  - python-termstyle==0.1.10
  - pyyaml==3.12
  - pyzmq==16.0.2
  - qt=5.6.2=5
  - qtconsole==4.3.1
  - rdflib==4.2.2
  - requests-cache==0.4.13
  - requests-kerberos==0.11.0
  - requests-toolbelt==0.8.0
  - rfc3987==1.3.7
  - simplegeneric==0.8.1
  - simplejson==3.11.1
  - smart-open==1.5.3
  - sparkmagic==0.12.4
  - sparqlwrapper==1.8.0
  - strict-rfc3339==0.7
  - swagger-spec-validator==2.1.0
  - terminado==0.6
  - testpath==0.3.1
  - tornado==4.5.2
  - tqdm==4.18.0
  - traitlets==4.3.2
  - twine==1.9.1
  - typing==3.6.2
  - unidecode==0.4.21
  - urllib3==1.21.1
  - watchdog==0.8.3
  - wcwidth==0.1.7
  - webcolors==1.7
  - webencodings==0.5.1
  - werkzeug==0.12.2
  - widgetsnbextension==2.0.1
prefix: /home/bizon/anaconda2/envs/robokop

