version: "3"
services:
  build_cache:
    image: redis
    container_name: build_cache
    command: redis-server --port ${BUILD_CACHE_PORT}
        
  interfaces:
    container_name: interfaces
    build:
      context: .
    env_file:
      - ../../shared/robokop.env
    environment:
      - DEPLOY=docker
      - ROBOKOP_HOME=/home/murphy
    ports:
      - "${BUILDER_PORT}:${BUILDER_PORT}"
      - "${BUILDER_SUPERVISOR_PORT}:${BUILDER_SUPERVISOR_PORT}"
    volumes:
      - ../../logs:/home/murphy/logs
      - ../../shared:/home/murphy/shared
      - ../:/home/murphy/robokop-interfaces